# Generated by Django 3.1.1 on 2020-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата создания'),
        ),
    ]
